# Generated by Django 4.2.7 on 2023-12-03 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uploadeddata_model_type_uploadeddata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadeddata',
            name='user',
        ),
    ]
