# Generated by Django 4.2.7 on 2023-12-03 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_uploadeddata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddata',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
