# Generated by Django 4.2.7 on 2023-12-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_uploadeddata_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddata',
            name='model_type',
            field=models.CharField(choices=[('linear_regression', 'Линейная Регрессия'), ('decision_tree', 'Решающее Дерево')], max_length=100),
        ),
    ]
