# Generated by Django 4.2.7 on 2023-12-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_uploadeddata_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddata',
            name='ACCURACY',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddata',
            name='DAVIES',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddata',
            name='F1',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddata',
            name='INTERIA',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddata',
            name='MAE',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddata',
            name='MSE',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddata',
            name='PRECISION',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddata',
            name='RECALL',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddata',
            name='ROC',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddata',
            name='RSQUARE',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddata',
            name='SILHUETTE',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddata',
            name='target_variable',
            field=models.CharField(default='y', max_length=100),
        ),
    ]
