# Generated by Django 4.2.7 on 2023-12-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_uploadeddata_accuracy_uploadeddata_davies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddata',
            name='model_type',
            field=models.CharField(choices=[('linear_regression', 'Линейная Регрессия'), ('decision_tree', 'Решающее Дерево'), ('logistic_regression', 'Логистическая Регрессия'), ('svm', 'Метод Опорных Векторов')], max_length=100),
        ),
    ]
