# Generated by Django 4.2.7 on 2023-12-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_uploadeddata_model_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadeddata',
            name='INTERIA',
        ),
        migrations.AlterField(
            model_name='uploadeddata',
            name='model_type',
            field=models.CharField(choices=[('linear_regression', 'Линейная Регрессия'), ('decision_tree', 'Решающее Дерево'), ('logistic_regression', 'Логистическая Регрессия'), ('svm', 'Метод Опорных Векторов'), ('knn', 'K-Ближайших Соседей'), ('kmeans', 'Методы Кластеризации'), ('gradient_boosting', 'Градиентный Бустинг'), ('neural_network', 'Нейронные Сети')], max_length=100),
        ),
    ]
