# Generated by Django 4.2.7 on 2023-12-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_uploadeddata_interia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddata',
            name='INTERIA',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
    ]
