# Generated by Django 4.2.7 on 2023-12-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_uploadeddata_interia'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddata',
            name='graph_file',
            field=models.FileField(blank=True, null=True, upload_to='graphs/'),
        ),
    ]
